<<<<<<< HEAD
VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes
QMK_SETTINGS = yes
TAP_DANCE_ENABLE = no
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = no
=======
VIA_ENABLE=yes
VIAL_ENABLE=yes
LTO_ENABLE = yes
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
QMK_SETTINGS = no
>>>>>>> 6085c442ceddc80644ba290359ae69bbf0996652
